-- AI Interview Arena: second batch of question-bank questions so every role
-- has enough technical questions at every difficulty, plus more managerial,
-- behavioral and HR questions for all roles.

insert into public.question_bank (question, job_role, skill, difficulty, interview_type, expected_answer) values
-- Full Stack Developer
('What happens when you type a URL into the browser and press Enter?', 'Full Stack Developer', 'HTML', 'easy', 'technical',
 'DNS lookup, TCP/TLS handshake, HTTP request, server processing, response with status and headers, browser parses HTML, fetches CSS/JS, builds DOM/CSSOM, renders; caching at several layers.'),
('What is the difference between SQL and NoSQL databases? When would you pick each?', 'Full Stack Developer', 'SQL', 'medium', 'technical',
 'SQL: relational tables, fixed schema, joins, ACID transactions — good for structured, related data. NoSQL: documents/key-value/graph, flexible schema, horizontal scaling — good for varied or high-volume data. Choice depends on data shape, consistency needs and query patterns.'),
('How would you secure a REST API against common attacks?', 'Full Stack Developer', 'REST APIs', 'hard', 'technical',
 'Authentication and authorisation on every endpoint, input validation, parameterised queries (SQL injection), output encoding (XSS), CSRF protection for cookies, rate limiting, HTTPS, least-privilege secrets, security headers, logging and dependency updates.'),
('How would you implement real-time notifications in a web app?', 'Full Stack Developer', 'System Design', 'hard', 'technical',
 'WebSockets or Server-Sent Events (or a managed service), connection per user with auth, a pub/sub layer (e.g. Redis) to fan out across servers, fallbacks and reconnection, persistence of unread notifications, and scaling considerations.'),
('Explain how you would add caching to speed up a slow API endpoint.', 'Full Stack Developer', 'Redis', 'medium', 'technical',
 'Identify cacheable reads, choose layer (HTTP cache headers, CDN, in-memory, Redis), cache key design, TTL and invalidation on writes, avoiding stale or per-user data leaks, measuring hit rate and latency.'),
('What are Promises and async/await in JavaScript?', 'Full Stack Developer', 'JavaScript', 'easy', 'technical',
 'A Promise represents a future value (pending, fulfilled, rejected); .then/.catch chain results. async functions return Promises and await pauses until a Promise settles, making async code read sequentially; handle errors with try/catch; Promise.all for parallel work.'),

-- Frontend Developer
('What is the virtual DOM and why does React use it?', 'Frontend Developer', 'React', 'medium', 'technical',
 'An in-memory tree of UI elements; React re-renders to a new tree, diffs it with the previous one (reconciliation) and applies minimal DOM updates. Keys help identify list items; the benefit is a simpler declarative model with efficient updates.'),
('Explain CSS Flexbox vs Grid. When would you use each?', 'Frontend Developer', 'CSS', 'easy', 'technical',
 'Flexbox is one-dimensional (row or column), good for aligning items in a line; Grid is two-dimensional (rows and columns), good for page or card layouts. They combine well: Grid for layout, Flexbox inside components.'),
('How do you manage state in a large React application?', 'Frontend Developer', 'React', 'hard', 'technical',
 'Keep state close to where it is used, lift when shared, Context for low-frequency global values, a store (Redux Toolkit, Zustand) for complex client state, a server-state library (React Query/SWR) for fetched data, and avoid duplicating derived state.'),
('What are Core Web Vitals and how do you improve them?', 'Frontend Developer', 'JavaScript', 'hard', 'technical',
 'LCP (loading: optimise images, server response, critical CSS), INP (interactivity: reduce long tasks, split JS), CLS (visual stability: set sizes for media, avoid injecting content above). Measure with Lighthouse and field data.'),
('How would you build a reusable, accessible modal dialog component?', 'Frontend Developer', 'HTML', 'expert', 'technical',
 'Use the native dialog element or role="dialog" with aria-modal and a label, move focus in and trap it, restore focus on close, close on Escape, prevent background scroll, render in a portal, and make it composable via props/children.'),
('What is the difference between == and === in JavaScript?', 'Frontend Developer', 'JavaScript', 'easy', 'technical',
 '== compares after type coercion (e.g. "1" == 1 is true); === compares value and type without coercion. Prefer === to avoid surprising results.'),

-- Backend Developer
('What is the difference between authentication and authorization?', 'Backend Developer', 'REST APIs', 'easy', 'technical',
 'Authentication verifies who the user is (login, tokens); authorization decides what they may do (roles, permissions, ownership checks). Authorization must be enforced on the server for every request.'),
('What are database transactions and ACID properties?', 'Backend Developer', 'SQL', 'medium', 'technical',
 'A transaction groups operations into one unit. Atomicity (all or nothing), Consistency (constraints hold), Isolation (concurrent transactions do not interfere, isolation levels), Durability (committed data survives crashes).'),
('How would you design a scalable file upload service?', 'Backend Developer', 'System Design', 'hard', 'technical',
 'Direct uploads to object storage with pre-signed URLs, size/type validation, virus scanning, metadata in a database, async processing via a queue, CDN for downloads, access control, and retries for large files (multipart/resumable uploads).'),
('Explain the event loop in Node.js.', 'Backend Developer', 'Node.js', 'medium', 'technical',
 'Single-threaded loop that runs callbacks from queues in phases (timers, I/O callbacks, poll, check, close); microtasks (Promises, process.nextTick) run between; blocking CPU work stalls everything, so offload it to worker threads.'),
('How would you handle database migrations safely in production?', 'Backend Developer', 'PostgreSQL', 'expert', 'technical',
 'Version-controlled migrations, backward-compatible changes (expand/contract), avoid long locks (create index concurrently, batch backfills), test on a copy, deploy migrations before code that needs them, have a rollback plan and backups.'),

-- Data Analyst
('What is the difference between WHERE and HAVING?', 'Data Analyst', 'SQL', 'easy', 'technical',
 'WHERE filters rows before grouping; HAVING filters groups after GROUP BY, so it can use aggregates like COUNT or SUM.'),
('How would you explain a correlation to a stakeholder without implying causation?', 'Data Analyst', 'Statistics', 'medium', 'technical',
 'Describe the relationship and its strength, note that other factors may drive both, give an example of a confounder, and suggest how causation could be tested (experiment or controlled analysis).'),
('Which chart would you use to compare categories, show a trend and show a distribution?', 'Data Analyst', 'Tableau', 'easy', 'technical',
 'Bar chart for comparing categories, line chart for trends over time, histogram or box plot for distributions; avoid pie charts with many slices and keep axes honest.'),
('How do you clean and validate a dataset before analysis?', 'Data Analyst', 'Excel', 'medium', 'technical',
 'Check types and formats, remove duplicates, handle missing values, detect outliers, standardise categories and dates, validate totals against a trusted source, and document every transformation.'),
('How would you calculate customer retention and churn from transaction data?', 'Data Analyst', 'SQL', 'hard', 'technical',
 'Define active customers per period, build cohorts by first purchase, compute the share still active in later periods (retention) and the share lost (churn), using window functions or date-truncated joins; watch definitions and seasonality.'),

-- Data Scientist
('What is cross-validation and why is it used?', 'Data Scientist', 'Machine Learning', 'easy', 'technical',
 'Splitting data into k folds, training on k-1 and validating on the rest, repeated k times, to estimate generalisation performance more reliably than a single split and to tune hyperparameters without leaking the test set.'),
('Explain the difference between L1 and L2 regularisation.', 'Data Scientist', 'Machine Learning', 'medium', 'technical',
 'Both add a penalty on weights to reduce overfitting. L1 (lasso) uses absolute values and drives some weights to zero (feature selection); L2 (ridge) uses squares and shrinks weights smoothly.'),
('How would you detect and handle data leakage?', 'Data Scientist', 'Machine Learning', 'hard', 'technical',
 'Leakage is information from the future or the target entering features. Detect via suspiciously high scores and feature importance; prevent by splitting before preprocessing, time-based splits, pipelines, and reviewing how each feature is generated.'),
('What is a p-value and what are its limitations?', 'Data Scientist', 'Statistics', 'medium', 'technical',
 'The probability of results at least as extreme as observed if the null hypothesis is true. It is not the probability the hypothesis is true, depends on sample size, and should be reported with effect sizes and confidence intervals.'),
('How would you build a recommendation system for an e-commerce site?', 'Data Scientist', 'Machine Learning', 'expert', 'technical',
 'Start with popularity baselines, then collaborative filtering (matrix factorisation) and content-based features, hybrid models, handle cold start, evaluate offline (precision@k, recall@k) and online (A/B tests), and monitor for feedback loops.'),

-- AI/ML Engineer
('What is gradient descent?', 'AI/ML Engineer', 'Machine Learning', 'easy', 'technical',
 'An optimisation method that updates parameters in the direction that reduces the loss, scaled by a learning rate; variants include batch, stochastic and mini-batch, and optimisers like Adam adapt the step size.'),
('What are embeddings and how are they used?', 'AI/ML Engineer', 'NLP', 'medium', 'technical',
 'Dense vectors that represent items (words, sentences, images) so similar items are close; used for semantic search, clustering, recommendations and as model inputs; compared with cosine similarity.'),
('How would you fine-tune a pre-trained model for a text classification task?', 'AI/ML Engineer', 'Deep Learning', 'hard', 'technical',
 'Prepare labelled data, tokenize, add a classification head, train with a small learning rate and early stopping, consider parameter-efficient methods (LoRA), evaluate on a held-out set, and watch for overfitting and class imbalance.'),
('How do you serve a machine learning model with low latency at scale?', 'AI/ML Engineer', 'Machine Learning', 'expert', 'technical',
 'Optimise the model (quantisation, distillation), batch requests, use GPUs or optimised runtimes (ONNX, TensorRT), cache results, autoscale, place close to users, and monitor latency percentiles and errors.'),
('Explain precision, recall and F1 in the context of a spam classifier.', 'AI/ML Engineer', 'Machine Learning', 'easy', 'technical',
 'Precision: share of emails flagged as spam that are spam; recall: share of spam that was caught; F1 is their harmonic mean. For spam, high precision avoids losing real emails.'),

-- Digital Marketing Executive
('What is the difference between organic and paid marketing?', 'Digital Marketing Executive', 'SEO', 'easy', 'technical',
 'Organic reaches people without paying per view (SEO, content, social posts) and builds over time; paid buys reach (search ads, social ads) for fast, targeted results that stop when spending stops. They work best together.'),
('How would you do keyword research for a new product page?', 'Digital Marketing Executive', 'SEO', 'medium', 'technical',
 'Understand user intent, brainstorm seed terms, use tools (Google Keyword Planner, Search Console) for volume and difficulty, check competitors, choose primary and long-tail keywords, and map them to page titles, headings and content.'),
('How do you measure the ROI of a digital marketing campaign?', 'Digital Marketing Executive', 'Google Analytics', 'hard', 'technical',
 'Define conversions and their value, track with UTM parameters and GA4 events, attribute revenue to channels, compare with total cost (ads, content, tools, time), and consider lifetime value and assisted conversions.'),
('What is A/B testing in email marketing and what would you test?', 'Digital Marketing Executive', 'Content Marketing', 'medium', 'technical',
 'Sending variants to random segments to compare performance: subject lines, send time, call to action, layout, personalisation; test one change at a time, use enough sample size, and pick the winner by the target metric.'),
('How would you grow an Instagram account for a small brand from scratch?', 'Digital Marketing Executive', 'Social Media Marketing', 'hard', 'technical',
 'Define audience and positioning, consistent content pillars and schedule, Reels and trends, hashtags and collaborations, engage with the community, run small paid boosts, and track reach, engagement and follower growth to iterate.'),

-- HR Executive
('What is the difference between onboarding and orientation?', 'HR Executive', 'Recruitment', 'easy', 'technical',
 'Orientation is a short introduction (policies, tour, paperwork) on the first days; onboarding is a longer process (weeks to months) that integrates the employee into their role, team and culture with goals and check-ins.'),
('How would you handle a complaint of harassment at work?', 'HR Executive', 'Employee Relations', 'hard', 'hr',
 'Take it seriously, ensure the complainant''s safety and confidentiality, follow policy and law, investigate impartially (interviews, evidence), document everything, take proportionate action, prevent retaliation and follow up.'),
('How do you conduct an effective exit interview?', 'HR Executive', 'Employee Relations', 'medium', 'hr',
 'Create a safe, confidential conversation, ask open questions about reasons, manager, growth and culture, listen without defending, record themes, and share aggregated insights to drive retention improvements.'),
('What key components make up an employee''s salary structure in India?', 'HR Executive', 'Payroll', 'medium', 'technical',
 'Basic pay, HRA, allowances (special, conveyance), bonuses and incentives, and deductions such as provident fund, professional tax, income tax (TDS) and ESI where applicable; CTC vs take-home.'),
('How would you measure the effectiveness of a training program?', 'HR Executive', 'Recruitment', 'hard', 'managerial',
 'Use a model like Kirkpatrick: reaction (feedback), learning (assessments), behaviour (on-the-job change), results (business impact such as productivity or retention); set goals before training and compare against a baseline.'),

-- Business Development Executive
('How do you research a prospect before a first meeting?', 'Business Development Executive', 'Lead Generation', 'easy', 'technical',
 'Study the company (website, news, financials), the person (LinkedIn role, interests), their industry challenges and competitors, and prepare tailored questions and a hypothesis of how you can help.'),
('What is a sales pipeline and which metrics would you track?', 'Business Development Executive', 'CRM', 'medium', 'technical',
 'The stages a deal moves through (lead, qualified, proposal, negotiation, closed). Track number and value of deals per stage, conversion rates, average deal size, sales cycle length and win rate.'),
('How would you structure a proposal for a large enterprise client?', 'Business Development Executive', 'Negotiation', 'hard', 'technical',
 'Executive summary tied to their goals, understanding of their problem, proposed solution and scope, timeline, pricing options, ROI and case studies, risks and mitigation, and clear next steps.'),
('How do you handle a situation where you are about to miss your quarterly target?', 'Business Development Executive', 'Time Management', 'medium', 'behavioral',
 'Review the pipeline honestly, prioritise deals closest to closing, accelerate with the right stakeholders, ask for help early, avoid unhealthy discounting, and communicate transparently with the manager with a recovery plan.'),

-- All roles
('Tell me about a time you worked in a team with a difficult colleague.', null, 'Teamwork', 'medium', 'behavioral',
 'STAR structure, empathy for the colleague''s view, direct but respectful conversation, focus on shared goals, the outcome and what the candidate learned.'),
('Describe a goal you set and how you achieved it.', null, 'Time Management', 'easy', 'behavioral',
 'A specific, measurable goal, the plan and milestones, obstacles and how they were overcome, the result and reflection.'),
('What motivates you at work?', null, 'Communication', 'easy', 'hr',
 'Genuine motivations linked to the role (learning, impact, solving problems, teamwork) with a short example.'),
('Why should we hire you for this role?', null, 'Communication', 'medium', 'hr',
 'Connects specific skills and achievements to the job requirements, shows understanding of the company''s needs and what makes the candidate different.'),
('How would you delegate tasks in a team with mixed experience levels?', null, 'Leadership', 'medium', 'managerial',
 'Match tasks to skills and growth goals, give clear outcomes and deadlines, pair juniors with mentors, stay available, check progress without micromanaging and recognise results.'),
('How do you set goals and measure performance for your team?', null, 'Leadership', 'hard', 'managerial',
 'Align with company objectives, use SMART goals or OKRs, agree on measurable key results, hold regular one-to-ones, give continuous feedback and review fairly with data.'),
('A key team member suddenly resigns before a major delivery. What do you do?', null, 'Problem Solving', 'expert', 'managerial',
 'Understand the reason and try a retention conversation if appropriate, secure knowledge transfer, re-plan scope and priorities, redistribute work or bring in help, communicate with stakeholders early, and start hiring.'),
('Describe a time you received critical feedback. How did you respond?', null, 'Communication', 'medium', 'behavioral',
 'Listened without defending, asked clarifying questions, acknowledged valid points, made a concrete change and followed up; shows a growth mindset.'),
('Tell me about a time you went beyond what was expected.', null, 'Problem Solving', 'medium', 'behavioral',
 'A specific situation, why extra effort mattered, what was done beyond the requirement, measurable impact and balance with other responsibilities.');
