-- AI Interview Arena: starter data.
-- A shared skills vocabulary and a question bank covering every job role,
-- interview type and difficulty. Admins can edit all of it from the app.

insert into public.skills (name, category) values
  ('JavaScript', 'Programming'), ('TypeScript', 'Programming'), ('Python', 'Programming'),
  ('Java', 'Programming'), ('SQL', 'Data'), ('React', 'Frontend'), ('Next.js', 'Frontend'),
  ('HTML', 'Frontend'), ('CSS', 'Frontend'), ('Tailwind CSS', 'Frontend'),
  ('Node.js', 'Backend'), ('Express', 'Backend'), ('REST APIs', 'Backend'),
  ('GraphQL', 'Backend'), ('PostgreSQL', 'Data'), ('MongoDB', 'Data'), ('Redis', 'Backend'),
  ('Docker', 'DevOps'), ('Git', 'Tools'), ('AWS', 'Cloud'), ('System Design', 'Engineering'),
  ('Excel', 'Data'), ('Power BI', 'Data'), ('Tableau', 'Data'), ('Pandas', 'Data'),
  ('Statistics', 'Data'), ('Machine Learning', 'AI'), ('Deep Learning', 'AI'),
  ('TensorFlow', 'AI'), ('PyTorch', 'AI'), ('NLP', 'AI'), ('LLMs', 'AI'),
  ('SEO', 'Marketing'), ('Google Ads', 'Marketing'), ('Social Media Marketing', 'Marketing'),
  ('Content Marketing', 'Marketing'), ('Google Analytics', 'Marketing'),
  ('Recruitment', 'HR'), ('Employee Relations', 'HR'), ('Payroll', 'HR'),
  ('Lead Generation', 'Sales'), ('Negotiation', 'Sales'), ('CRM', 'Sales'),
  ('Communication', 'Soft skills'), ('Leadership', 'Soft skills'),
  ('Problem Solving', 'Soft skills'), ('Teamwork', 'Soft skills'), ('Time Management', 'Soft skills')
on conflict do nothing;

insert into public.question_bank (question, job_role, skill, difficulty, interview_type, expected_answer) values
-- Full Stack Developer
('Explain the difference between let, var and const in JavaScript.', 'Full Stack Developer', 'JavaScript', 'easy', 'technical',
 'var is function-scoped and hoisted (initialised as undefined); let and const are block-scoped and in the temporal dead zone until declared. const cannot be reassigned, but objects it holds can still be mutated. Prefer const, then let; avoid var.'),
('What is a REST API? Give a real-world example.', 'Full Stack Developer', 'REST APIs', 'easy', 'technical',
 'An architectural style over HTTP where resources are identified by URLs and manipulated with methods (GET, POST, PUT/PATCH, DELETE). Stateless requests, standard status codes, usually JSON. Example: GET /orders/42 returns an order; POST /orders creates one.'),
('How would you design authentication for a web application?', 'Full Stack Developer', 'System Design', 'medium', 'technical',
 'Hash passwords with bcrypt/argon2, never store plain text. Session cookies (httpOnly, secure, sameSite) or short-lived JWT + refresh token. HTTPS only, rate-limit login, CSRF protection for cookies, password reset via one-time expiring token, optional MFA, role-based authorisation checked on the server.'),
('How would you optimize a slow database query?', 'Full Stack Developer', 'SQL', 'medium', 'technical',
 'Measure with EXPLAIN ANALYZE; look for sequential scans. Add indexes on filter/join/sort columns (composite where useful), select only needed columns, avoid N+1 queries, paginate, rewrite subqueries as joins, cache hot reads, and re-measure. Mention index trade-off on writes.'),
('Design a URL shortener. What are the main components and trade-offs?', 'Full Stack Developer', 'System Design', 'hard', 'technical',
 'API to create/resolve, key generation (base62 counter or hash with collision check), key-value store, redirect with 301/302, cache for hot links, analytics pipeline asynchronous, rate limiting, expiry. Trade-offs: predictability of counters vs collisions of hashes, consistency vs latency, read-heavy scaling with caching/CDN.'),
('How do you keep state consistent between the client and server in a React application that edits shared data?', 'Full Stack Developer', 'React', 'expert', 'technical',
 'Treat server as source of truth; use a data layer with caching and invalidation (React Query/SWR or server components with revalidation). Optimistic updates with rollback, versioning/ETags or updated_at checks to detect conflicts, real-time sync via websockets when needed, idempotent mutations, and clear loading/error states.'),
('Tell me about a project where you owned a feature end to end. What would you do differently now?', 'Full Stack Developer', 'Communication', 'medium', 'behavioral',
 'Uses a clear structure (situation, task, action, result), explains technical decisions and their reasons, quantifies impact, shows reflection with concrete improvements and lessons learned.'),

-- Frontend Developer
('What is a React hook? Give an example.', 'Frontend Developer', 'React', 'easy', 'technical',
 'Functions that let function components use state and lifecycle features: useState, useEffect, useMemo, useRef, custom hooks. Rules: call at top level, only from components or other hooks. Example: useState for a counter, useEffect to fetch data with cleanup.'),
('Explain the CSS box model.', 'Frontend Developer', 'CSS', 'easy', 'technical',
 'Every element is content + padding + border + margin. box-sizing: content-box (width = content) vs border-box (width includes padding and border). Margins can collapse vertically between block elements.'),
('What is the difference between state and props in React?', 'Frontend Developer', 'React', 'easy', 'technical',
 'Props are inputs passed from parent, read-only for the child. State is owned by a component and changes over time, triggering re-render. Lift state up to share it; pass data down via props and changes up via callbacks.'),
('How would you improve the performance of a slow page?', 'Frontend Developer', 'JavaScript', 'medium', 'technical',
 'Measure first (Lighthouse, Web Vitals, profiler). Reduce bundle size (code splitting, tree shaking), optimise images (modern formats, lazy loading, sizes), cache and preload critical resources, avoid unnecessary re-renders (memoisation, virtualised lists), defer non-critical scripts, reduce layout shift.'),
('How do you make a web application accessible?', 'Frontend Developer', 'HTML', 'medium', 'technical',
 'Semantic HTML, labels for inputs, keyboard navigation and visible focus, sufficient colour contrast, alt text, ARIA only when needed, announce dynamic changes, respect reduced motion, test with screen readers and axe/Lighthouse.'),
('Explain how the browser renders a page, from HTML to pixels.', 'Frontend Developer', 'HTML', 'hard', 'technical',
 'Parse HTML to DOM and CSS to CSSOM, combine into render tree, layout (reflow) computes geometry, paint fills pixels, compositing layers on the GPU. JavaScript can block parsing; changing layout properties triggers reflow, transforms/opacity only compositing.'),
('Describe a time you disagreed with a designer about a UI decision. How did you resolve it?', 'Frontend Developer', 'Teamwork', 'medium', 'behavioral',
 'Shows respect and curiosity about the designer''s intent, backs position with data (usability, accessibility, effort), proposes alternatives or a quick test, reaches a shared decision and reflects on the outcome.'),

-- Backend Developer
('What are HTTP status codes? Which would you return for validation errors and missing resources?', 'Backend Developer', 'REST APIs', 'easy', 'technical',
 '2xx success (200 OK, 201 Created, 204 No Content), 3xx redirects, 4xx client errors (400 Bad Request or 422 Unprocessable Entity for validation, 401 unauthenticated, 403 forbidden, 404 not found, 409 conflict, 429 too many requests), 5xx server errors.'),
('How would you index a slow SQL query?', 'Backend Developer', 'SQL', 'medium', 'technical',
 'Inspect the plan with EXPLAIN ANALYZE, index columns used in WHERE, JOIN and ORDER BY, use composite indexes in the right column order, consider partial/covering indexes, verify the planner uses them, and weigh write overhead and storage.'),
('Explain the difference between processes and threads, with an example from Node.js.', 'Backend Developer', 'Node.js', 'medium', 'technical',
 'A process has its own memory space; threads share memory within a process. Node runs JavaScript on a single main thread with an event loop, uses libuv''s thread pool for file/crypto work, and worker_threads or child processes for CPU-heavy tasks.'),
('Design a rate limiter for a public REST API.', 'Backend Developer', 'System Design', 'hard', 'technical',
 'Algorithms: token bucket, leaky bucket, fixed/sliding window. Key by API key or IP, store counters in Redis with atomic operations (INCR/Lua), return 429 with Retry-After, handle distributed servers with a shared store, fail-open vs fail-closed choice, different tiers per plan.'),
('How would you guarantee exactly-once processing of payments in a distributed system?', 'Backend Developer', 'System Design', 'expert', 'technical',
 'True exactly-once is impractical; achieve effectively-once with idempotency keys, deduplication tables, transactional outbox, at-least-once delivery with idempotent consumers, database constraints, and reconciliation jobs. Discuss retries, timeouts and failure modes.'),
('How would you lead a team through a missed deadline?', null, 'Leadership', 'medium', 'managerial',
 'Acknowledge early and transparently to stakeholders, find root causes without blame, re-plan scope and priorities, communicate a realistic new date, support the team, and put process improvements in place to prevent repeats.'),
('Tell me about a production incident you handled.', 'Backend Developer', 'Problem Solving', 'hard', 'behavioral',
 'Describes detection, impact assessment, communication, mitigation first then root cause, a blameless post-mortem and concrete follow-up actions such as monitoring or tests.'),

-- Data Analyst
('What is normalization in SQL?', 'Data Analyst', 'SQL', 'medium', 'technical',
 'Organising tables to reduce redundancy and update anomalies: 1NF atomic values, 2NF no partial dependency on a composite key, 3NF no transitive dependencies. Trade-off: more joins; analytics often denormalises for speed.'),
('Explain the difference between INNER JOIN and LEFT JOIN with an example.', 'Data Analyst', 'SQL', 'easy', 'technical',
 'INNER JOIN returns only rows with matches in both tables; LEFT JOIN returns all rows from the left table with NULLs where there is no match. Example: customers LEFT JOIN orders shows customers without orders.'),
('How do you handle missing values in a dataset?', 'Data Analyst', 'Pandas', 'medium', 'technical',
 'First understand why data is missing (MCAR/MAR/MNAR). Options: remove rows/columns if small impact, impute with mean/median/mode or model-based methods, add an indicator column, or keep as a category. Document choices and check how they affect results.'),
('How would you design a dashboard to track weekly sales performance?', 'Data Analyst', 'Power BI', 'medium', 'technical',
 'Start from the audience and decisions; choose KPIs (revenue, units, conversion, vs target and last period), filters (region, product, date), clear visuals (trend lines, bar comparisons), consistent definitions, refresh schedule and data quality checks.'),
('A metric suddenly dropped by 20% this week. How do you investigate?', 'Data Analyst', 'Problem Solving', 'hard', 'technical',
 'Check data quality and pipeline first, then segment by time, region, platform, channel and product, compare with seasonality and releases/campaigns, form and test hypotheses, quantify impact, and communicate findings with recommended actions.'),
('Explain window functions and give a use case.', 'Data Analyst', 'SQL', 'expert', 'technical',
 'Functions computed over a set of rows related to the current row without collapsing them: ROW_NUMBER, RANK, LAG/LEAD, running SUM with OVER (PARTITION BY … ORDER BY …). Use cases: running totals, top-N per group, period-over-period change.'),
('Tell me about a time your analysis changed a business decision.', 'Data Analyst', 'Communication', 'medium', 'behavioral',
 'Explains the business question, data and method, the insight, how it was communicated to stakeholders, the decision taken and the measurable result.'),

-- Data Scientist
('Explain the bias-variance trade-off.', 'Data Scientist', 'Machine Learning', 'medium', 'technical',
 'Bias is error from overly simple assumptions (underfitting); variance is sensitivity to training data (overfitting). Increasing model complexity lowers bias but raises variance. Balance using cross-validation, regularisation, more data or ensembles.'),
('What is the difference between precision and recall? When would you prioritise each?', 'Data Scientist', 'Statistics', 'easy', 'technical',
 'Precision = TP / (TP + FP), recall = TP / (TP + FN). Prioritise recall when missing positives is costly (disease screening, fraud), precision when false alarms are costly (spam filtering). F1 balances both; choose threshold with the business cost.'),
('How would you evaluate an A/B test?', 'Data Scientist', 'Statistics', 'medium', 'technical',
 'Define hypothesis and primary metric, calculate sample size and power beforehand, randomise properly, run for full cycles, check sample ratio mismatch, use appropriate test (t-test, chi-square), report confidence intervals and practical significance, avoid peeking and multiple-testing pitfalls.'),
('How do you handle an imbalanced classification dataset?', 'Data Scientist', 'Machine Learning', 'hard', 'technical',
 'Use suitable metrics (PR-AUC, recall, F1 instead of accuracy), resampling (oversampling, SMOTE, undersampling), class weights, threshold tuning, stratified cross-validation, and collecting more minority data where possible.'),
('How would you deploy and monitor a machine learning model in production?', 'Data Scientist', 'Machine Learning', 'expert', 'technical',
 'Package model with versioned data and code, serve via batch or API, validate inputs, monitor latency, errors, data drift and prediction drift, track business metrics, set up retraining pipelines and rollback, and log for auditability.'),
('Explain a complex model result to a non-technical stakeholder.', 'Data Scientist', 'Communication', 'medium', 'behavioral',
 'Starts from the business question, avoids jargon, uses simple visuals and examples, explains confidence and limitations, and ends with a clear recommendation.'),

-- AI/ML Engineer
('Explain overfitting and how to prevent it.', 'AI/ML Engineer', 'Machine Learning', 'medium', 'technical',
 'Model memorises training data and generalises poorly (high train, low validation performance). Prevent with more data, augmentation, regularisation (L1/L2, dropout), early stopping, simpler models, cross-validation.'),
('What is the difference between supervised, unsupervised and reinforcement learning?', 'AI/ML Engineer', 'Machine Learning', 'easy', 'technical',
 'Supervised learns from labelled input-output pairs (classification, regression); unsupervised finds structure in unlabelled data (clustering, dimensionality reduction); reinforcement learns actions from rewards through interaction with an environment.'),
('How does the attention mechanism in transformers work?', 'AI/ML Engineer', 'Deep Learning', 'hard', 'technical',
 'Each token produces query, key and value vectors; attention weights = softmax(QK^T / sqrt(d_k)) applied to V, letting each token attend to all others. Multi-head attention learns different relations in parallel; positional encodings add order information.'),
('How would you build a retrieval-augmented generation (RAG) system over company documents?', 'AI/ML Engineer', 'LLMs', 'hard', 'technical',
 'Ingest and chunk documents, create embeddings and store in a vector database, retrieve top-k relevant chunks (optionally hybrid search and reranking), build a prompt with context, generate with an LLM, cite sources, evaluate retrieval and answer quality, handle access control and freshness.'),
('How would you reduce hallucinations and evaluate an LLM feature before launch?', 'AI/ML Engineer', 'LLMs', 'expert', 'technical',
 'Ground answers with retrieval and citations, constrain output with schemas, lower temperature, add refusal instructions, build an evaluation set with expected answers, use automatic and human grading, red-team, monitor in production and collect feedback.'),
('Tell me about a model that did not perform as expected. What did you do?', 'AI/ML Engineer', 'Problem Solving', 'medium', 'behavioral',
 'Describes diagnosing data issues, leakage or distribution shift, experiments tried, how results were communicated, and what was learned.'),

-- Digital Marketing Executive
('What is SEO and what are its main components?', 'Digital Marketing Executive', 'SEO', 'easy', 'technical',
 'Improving organic search visibility: technical SEO (crawlability, speed, mobile, structured data), on-page (keywords, titles, content quality, internal links), off-page (backlinks, authority). Measure with Search Console and analytics.'),
('How would you plan a social media campaign for a product launch?', 'Digital Marketing Executive', 'Social Media Marketing', 'medium', 'technical',
 'Define goals and KPIs, target audience and personas, choose platforms, content calendar (teasers, launch, follow-up), creatives and messaging, budget for paid promotion, influencer collaboration, tracking with UTM links and reporting.'),
('Explain CTR, CPC and ROAS. How would you improve a campaign with low ROAS?', 'Digital Marketing Executive', 'Google Ads', 'medium', 'technical',
 'CTR = clicks / impressions, CPC = cost / clicks, ROAS = revenue / ad spend. Improve by refining targeting and keywords, negative keywords, better ad copy and creatives, landing page conversion optimisation, bid strategy adjustments and pausing poor performers.'),
('How do you measure the success of a content marketing strategy?', 'Digital Marketing Executive', 'Google Analytics', 'hard', 'technical',
 'Tie metrics to goals: traffic and engagement (sessions, time on page, scroll depth), SEO rankings, leads and conversions, attribution, retention and share of voice. Use GA4 events, UTM tracking and regular content audits.'),
('Describe a campaign that did not go as planned and what you learned.', 'Digital Marketing Executive', 'Communication', 'medium', 'behavioral',
 'Honest about the problem, explains how data was used to diagnose it, corrective actions taken and specific lessons applied later.'),

-- HR Executive
('Describe a time you resolved a team conflict.', 'HR Executive', 'Employee Relations', 'medium', 'behavioral',
 'Listens to both sides privately, stays neutral, identifies underlying interests, facilitates a joint conversation, agrees on actions, documents and follows up; uses STAR structure and shows outcome.'),
('What are the key steps in a recruitment process?', 'HR Executive', 'Recruitment', 'easy', 'technical',
 'Workforce planning and job analysis, job description, sourcing (job boards, referrals, LinkedIn), screening, interviews and assessments, reference checks, offer and negotiation, onboarding; track metrics like time-to-hire and quality of hire.'),
('How would you reduce employee attrition in a team with high turnover?', 'HR Executive', 'Employee Relations', 'hard', 'managerial',
 'Analyse exit interviews and data to find causes, conduct stay interviews, improve onboarding, career paths and recognition, review compensation benchmarks, train managers, improve flexibility and wellbeing, and track retention metrics.'),
('How do you handle confidential employee information?', 'HR Executive', 'Employee Relations', 'medium', 'hr',
 'Share only on a need-to-know basis, follow data protection laws and company policy, secure storage and access controls, never discuss informally, and escalate breaches properly.'),
('How would you design an onboarding program for new hires?', 'HR Executive', 'Recruitment', 'medium', 'technical',
 'Pre-boarding (paperwork, equipment), first-day welcome, role clarity and 30-60-90 day goals, buddy/mentor, training plan, regular check-ins, and feedback surveys to improve the program.'),

-- Business Development Executive
('How do you generate and qualify new leads?', 'Business Development Executive', 'Lead Generation', 'easy', 'technical',
 'Sources: outbound prospecting, referrals, events, LinkedIn, inbound marketing. Qualify with frameworks like BANT or MEDDIC (budget, authority, need, timeline), score leads and focus on best-fit accounts, track in a CRM.'),
('Walk me through how you would handle a client objection about price.', 'Business Development Executive', 'Negotiation', 'medium', 'technical',
 'Acknowledge and clarify the concern, understand what they compare against, reframe around value and ROI, offer options (scope, terms, phased rollout) rather than discounting immediately, and confirm next steps.'),
('How would you enter a new market or territory with no existing clients?', 'Business Development Executive', 'Lead Generation', 'hard', 'managerial',
 'Research the market and competitors, define ideal customer profile, build a target list, partnerships and local networks, pilot offers and case studies, set measurable goals and adjust based on early feedback.'),
('Tell me about the biggest deal you closed. What made it successful?', 'Business Development Executive', 'Negotiation', 'medium', 'behavioral',
 'Explains the client need, stakeholders, sales process, obstacles and how they were handled, the result with numbers and what was learned.'),
('How do you use a CRM to manage your sales pipeline?', 'Business Development Executive', 'CRM', 'easy', 'technical',
 'Log every contact and activity, define pipeline stages, set follow-up reminders, forecast using stage probabilities, analyse conversion rates, and keep data clean for the team.'),

-- All roles: HR, behavioral, managerial
('Tell me about yourself.', null, 'Communication', 'easy', 'hr',
 'A concise 1-2 minute summary: current role or studies, relevant skills and experience, one or two achievements, and why this role is the next step. Stays relevant to the job.'),
('Why do you want to join our company?', null, 'Communication', 'easy', 'hr',
 'Shows research about the company, connects its mission, products or culture to own goals and skills, and explains the value they would bring.'),
('What are your strengths and weaknesses?', null, 'Communication', 'easy', 'hr',
 'Strengths backed by examples relevant to the role; a real weakness with concrete steps taken to improve it, not a disguised strength.'),
('Where do you see yourself in five years?', null, 'Communication', 'medium', 'hr',
 'Realistic growth goals aligned with the role and company, shows ambition and commitment to learning.'),
('Describe a situation where you had to learn something new quickly.', null, 'Problem Solving', 'medium', 'behavioral',
 'STAR structure, specific learning approach (resources, practice, asking for help), result and how the skill was used afterwards.'),
('Tell me about a time you made a mistake at work or in a project.', null, 'Communication', 'medium', 'behavioral',
 'Takes ownership, explains impact honestly, describes how it was fixed and the process change or lesson that prevents it happening again.'),
('How do you prioritise when you have several urgent tasks?', null, 'Time Management', 'medium', 'behavioral',
 'Clarifies deadlines and impact with stakeholders, uses a prioritisation method (urgent/important, effort vs value), communicates trade-offs early, and delegates or renegotiates when needed.'),
('How do you give difficult feedback to a team member?', null, 'Leadership', 'hard', 'managerial',
 'Prepares specific examples, delivers privately and promptly, focuses on behaviour and impact not personality, listens, agrees on actions and follows up; uses a model like SBI (situation, behaviour, impact).'),
('How would you motivate a team that is losing interest in a long project?', null, 'Leadership', 'hard', 'managerial',
 'Reconnect work to purpose and impact, break goals into visible milestones, celebrate progress, remove blockers, listen to concerns, rotate responsibilities and recognise contributions.'),
('How do you make a decision when you do not have all the information?', null, 'Problem Solving', 'expert', 'managerial',
 'Clarifies what is known, what is unknown and the cost of delay, gathers the most valuable information quickly, considers reversibility, decides with stated assumptions, communicates and sets checkpoints to revisit.');
